; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


;.if FAMISTUDIO_CFG_C_BINDINGS
;.export _sounds=sounds
;.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_konami_pause

@sfx_ntsc_konami_pause:
	.byte $81,$d5,$82,$00,$80,$be,$89,$f0,$01,$80,$bd,$01,$80,$bc,$01,$80
	.byte $bb,$01,$80,$b9,$01,$81,$8e,$80,$be,$01,$80,$bd,$01,$80,$bc,$01
	.byte $80,$bb,$01,$80,$b9,$01,$81,$a9,$80,$be,$01,$80,$bd,$01,$80,$bc
	.byte $01,$80,$bb,$01,$80,$b9,$01,$81,$6a,$80,$be,$02,$80,$bd,$02,$80
	.byte $bb,$02,$80,$ba,$02,$80,$b9,$02,$80,$b7,$02,$80,$b5,$02,$80,$b4
	.byte $02,$00

.export sounds
