; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

;.if FAMISTUDIO_CFG_C_BINDINGS
;.export _music_data_=music_data_
;.endif

music_data_:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Star Maze
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env20,@env10,@env13,@env1 ; 00 : Noise 1
	.word @env9,@env10,@env13,@env1 ; 01 : Noise 2
	.word @env3,@env10,@env13,@env1 ; 02 : Pulse 2 Intro
	.word @env4,@env10,@env13,@env1 ; 03 : Pulse 2 Close1
	.word @env16,@env10,@env13,@env1 ; 04 : Pulse 2 Close2
	.word @env8,@env10,@env14,@env6 ; 05 : Pulse 2 Long
	.word @env17,@env10,@env14,@env6 ; 06 : Pulse 2 ExLong
	.word @env0,@env10,@env14,@env1 ; 07 : Pulse 2 Med
	.word @env5,@env10,@env14,@env1 ; 08 : Pulse 2 Short
	.word @env2,@env10,@env15,@env1 ; 09 : Pulse 1 Bass
	.word @env7,@env10,@env13,@env1 ; 0a : Pulse 2 Intro2
	.word @env12,@env10,@env14,@env6 ; 0b : Pulse 2 Finale
	.word @env11,@env19,@env14,@env1 ; 0c : Pulse 1 Kick
	.word @env11,@env19,@env14,@env18 ; 0d : Triangle

@env0:
	.byte $00,$c6,$14,$c1,$00,$03
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $00,$cb,$02,$c6,$c6,$c3,$c3,$c0,$02,$c3,$02,$c0,$00,$0b
@env3:
	.byte $00,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c2,$02,$c1,$c1,$c0,$00,$0c
@env4:
	.byte $00,$c7,$c6,$c5,$c2,$02,$c1,$00,$06
@env5:
	.byte $00,$c6,$0e,$c1,$00,$03
@env6:
	.byte $00,$c0,$1a,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$c1,$c2,$c2,$c0,$c0,$bf,$bf,$be,$be,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$c0,$c0,$c1,$00,$8f
@env7:
	.byte $00,$c7,$c6,$c5,$c2,$02,$c1,$c7,$c6,$c5,$c2,$02,$c1,$c0,$00,$0d
@env8:
	.byte $00,$c6,$1e,$c1,$00,$03
@env9:
	.byte $00,$c4,$05,$c3,$05,$c2,$00,$05
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $00,$cb,$02,$c0,$00,$03
@env12:
	.byte $00,$c6,$7d,$c1,$29,$c0,$00,$05
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $c1,$7f,$00,$00
@env16:
	.byte $00,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$02,$c2,$02,$c1,$c1,$c0,$00,$0e
@env17:
	.byte $00,$c6,$53,$c1,$17,$c0,$00,$05
@env18:
	.byte $00,$be,$a0,$d7,$be,$00,$04
@env19:
	.byte $c0,$bf,$bd,$c0,$00,$03
@env20:
	.byte $00,$c4,$c3,$c2,$c1,$c0,$02,$c1,$04,$c0,$00,$09

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $92
@song0ref6:
	.byte $0a, $a7, $07, $a7, $05, $b5, $07, $99, $0a, $99, $0c, $99, $0a, $a7, $07, $a7, $05, $b5, $07, $99, $0a, $99, $07, $99
	.byte $48, $05, $a7, $02, $a7, $40, $0c, $b5, $02, $99, $05, $99, $07, $99, $05, $a7, $02, $a7, $40, $0c, $b5, $02, $99, $05
	.byte $99, $07, $99, $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
@song0ref73:
	.byte $48, $98, $0a, $b5, $0a, $b5, $0a, $b5, $0a, $b5, $0a, $b5, $0a, $b5, $0a, $b5, $0a, $b5, $48, $0a, $b5, $0a, $b5, $0a
	.byte $b5, $0a, $b5, $0a, $b5, $0a, $a7, $92, $05, $8b, $05, $99, $07, $99, $0a, $99, $0c, $99, $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
	.byte $48
	.byte $41, $30
	.word @song0ref6
	.byte $41, $26
	.word @song0ref73
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref142:
	.byte $84
@song0ref143:
	.byte $39, $99, $37, $99, $35, $99, $86, $37, $8b, $88, $39, $a7, $84, $37, $99, $35, $99, $37, $99, $39, $99, $37, $99, $35
	.byte $99, $86, $37, $8b, $88, $39, $a7, $84, $37, $99, $35, $99, $37, $99, $3a, $99, $37, $99, $35, $99, $86, $37, $8b, $88
	.byte $3a, $a7, $84, $37, $99, $35, $99, $37, $99, $3a, $99, $37, $99, $35, $99, $86, $37, $8b, $88, $3a, $a7, $84, $37, $99
	.byte $35, $99, $37, $99
	.byte $41, $30
	.word @song0ref143
@song0ref222:
	.byte $94, $29, $8b, $29, $8b, $35, $8b, $35, $8b, $40, $4d, $8b, $40, $4d, $a7, $8e, $24, $b5, $30, $b5, $8a, $2d, $d1, $8c
	.byte $29, $ff, $f9, $90, $26, $a7, $29, $a7, $2b, $99, $8a, $24, $d1, $8c, $22, $ff, $f9, $8e, $24, $b5, $30, $b5, $8a, $2d
	.byte $d1, $8c, $29, $ff, $c1, $90, $26, $b5, $29, $b5, $2b, $b5, $8a, $24, $d1, $96, $22, $ff, $ff, $e9
	.byte $41, $40
	.word @song0ref142
	.byte $41, $30
	.word @song0ref143
	.byte $41, $35
	.word @song0ref222
	.byte $41, $40
	.word @song0ref142
	.byte $41, $30
	.word @song0ref143
	.byte $41, $35
	.word @song0ref222
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $9a
@song0ref313:
	.byte $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5, $16, $b5
	.byte $16, $b5, $16, $b5, $16, $b5, $16, $b5
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $ff, $ff, $ff, $bf, $ff, $ff, $cf
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $41, $20
	.word @song0ref313
	.byte $16, $b5, $16, $b5, $ff, $ff, $ff, $bf, $ff, $ff, $cf, $16, $b5, $16, $b5, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref398:
	.byte $80, $1f, $99, $82, $22, $99, $80, $1f, $99, $82, $22, $99, $80, $1f, $99, $82, $22, $99, $80, $1f, $99, $82, $22, $99
	.byte $80, $1f, $99, $82, $22, $99, $80, $1f, $99, $82, $22, $99, $80, $1f, $99, $82, $22, $99, $80, $1f, $99, $82, $22, $99
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $41, $20
	.word @song0ref398
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref519:
	.byte $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf
	.byte $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf
	.byte $41, $20
	.word @song0ref519
	.byte $41, $20
	.word @song0ref519
	.byte $42
	.word @song0ch4loop
